<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>bdb on 🤠 Major Hayden</title><link>https://major.io/tags/bdb/</link><description>Recent content in bdb on 🤠 Major Hayden</description><generator>Hugo -- gohugo.io</generator><language>en</language><copyright>All content licensed [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/)</copyright><lastBuildDate>Sun, 27 May 2007 16:38:32 +0000</lastBuildDate><atom:link href="https://major.io/tags/bdb/index.xml" rel="self" type="application/rss+xml"/><item><title>rpmdb: Lock table is out of available locker entries</title><link>https://major.io/2007/05/27/rpmdb-lock-table-is-out-of-available-locker-entries/</link><pubDate>Sun, 27 May 2007 16:38:32 +0000</pubDate><guid>https://major.io/2007/05/27/rpmdb-lock-table-is-out-of-available-locker-entries/</guid><description>If up2date throws some horrible Python errors and rpm says “rpmdb: Lock table is out of available locker entries”, you can restore your system to normality with the following:</description></item></channel></rss>